### ISSUE TITLE
Using tomcrypt or mbedtls

### ISSUE THREAD

**Issue by ZigFisher** [roleoroleo/onvif_simple_server#1]
Good afternoon !
Thank you very much for your project, it is very interesting.
Please tell me why you chose tomcrypt library and not mbedtls ? 
The second library is more widespread and used in many places. 
Maybe you have plans to switch to it in the future ?
Thank you.

**Comment by roleoroleo** [comment]
I don't know if I compiled mbedtls with the minimum set of features.
This is my config file:
```
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME_DATE
#define MBEDTLS_SHA1_C
#define MBEDTLS_BASE64_C
```

**Comment by ZigFisher** [comment]
Thank you very much for your reply.
I added your ONVIF solution to OpenIPC project recently.
https://github.com/OpenIPC/firmware/tree/master/general/package/onvif-simple-server
We use mbedtls internally and we are very interested in this solution.
I see your commit, I will try out the new solution soon and give feedback.
