### ISSUE TITLE
Segfault when using debug level 2..5

### ISSUE THREAD

**Issue by arkanoid87** [roleoroleo/onvif_simple_server#2]
Hi

thanks for working on a simple onvif server. I've been thinking about a template based approach for a while, but never found time to really start the project. May I ask how did you create the xml soap message templates?

heres the issue:

After first build, I noticed segfault when enabling -d 2 to 5. It doesn't segfault with -d 0  and 1

`onvif_simple_se[453568]: segfault at c0 ip 00007f0c67475078 sp 00007ffd22156df0 error 4 in libc.so.6[7f0c67428000+195000] likely on CPU 7 (core 1, socket 0)`

I would enable instrumentation but I'm not a C developer, please suggest me how to provide better debug info

**Comment by roleoroleo** [comment]
> May I ask how did you create the xml soap message templates?

Different sources: official onvif specifications, other open source projects, network capture between devices...

> After first build, I noticed segfault when enabling -d 2 to 5. It doesn't segfault with -d 0 and 1

How are you running the program?

**Comment by roleoroleo** [comment]
@onepif 
I will check the error.
Please open a new issue.
