### ISSUE TITLE
CGI pid XX died with signal 11

### ISSUE THREAD

**Issue by onepif** [roleoroleo/onvif_simple_server#4]
hi! When you launch the software on the camera (goke7205v300), the following happens (see screenshot).
for the test I ran it on arm64 - everything worked correctly there
What can be wrong?
![Screenshot_20240204_222157](https://github.com/roleoroleo/onvif_simple_server/assets/13848655/2bade3f9-d8b8-4e47-88ba-cd9c718e53c5)

**Comment by roleoroleo** [comment]
signal 11 is probably a seg fault. It's not normal
What client are you using?
You should send me some log.
Enable log:
`# echo 5 > /tmp/onvif_simple_server.debug`
read the log:
`# cat /tmp/onvif_simple_server.log`

and/or

capture the network traffic between the client and the server and send me the .pcap

**Comment by onepif** [comment]
[log+pcap.zip](https://github.com/roleoroleo/onvif_simple_server/files/14182469/log%2Bpcap.zip)

**Comment by roleoroleo** [comment]
The error is a "500 Internal Server Error".
And it's after a GetDeviceInformation request.
The code is ok, not completely safe but is ok.
Probably I should improve the control of the configuration file... next release.

Check the configuration file, especially the following options:
```
model=
manufacturer=
firmware_ver=
hardware_id=
serial_num=
```

**Comment by roleoroleo** [comment]
Check my last commits.
